licznik = 0
cena = float(input())
cena *= 100
while cena != 0:
    if cena >= 500:
        liczba = 500
        licznik += 1
        cena -= liczba
    elif 200 <= cena < 500:
        liczba = 200
        licznik += 1
        cena -= liczba
    elif 200 > cena >= 100:
        liczba = 100
        licznik += 1
        cena -= liczba
    elif 100 > cena >= 50:
        liczba = 50
        licznik += 1
        cena -= liczba
    elif 50 > cena >= 20:
        liczba = 20
        licznik += 1
        cena -= liczba
    elif 20 > cena >= 10:
        liczba = 10
        licznik += 1
        cena -= liczba
    elif 10 > cena >= 5:
        liczba = 5
        licznik += 1
        cena -= liczba
    elif 5 > cena >= 2:
        liczba = 2
        licznik += 1
        cena -= liczba
    elif 2 > cena >= 1:
        liczba = 1
        licznik += 1
        cena -= liczba

print(licznik)